# Site wide configuration

title: ACM Local
locale: en_US
description: Connecting smart technical people at local city events
logo: acmlogo_black.png
search: true
url: https://local.acm.org
#url: https://acmorg.github.io
#url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Association for Computing Machinery
  avatar: acmlogo.png
  email: adconk@staff.acm.org
  disqus-shortname:
  twitter: theofficialacm
  facebook: pages/ACM-Association-for-Computing-Machinery/17927643151
  github: acmorg
  stackexchange: #https://stackoverflow.com/users/123456/username
  linkedin: company/association-for-computing-machinery
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-54976316-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
